# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'projectApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for projectApp
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'projectAppTests' do
    inherit! :search_paths
    # Add the Firebase pod for Google Analytics
    # Pods for testing
  end

  target 'projectAppUITests' do
    # Add the Firebase pod for Google Analytics
    # Pods for testing
  end

end